### ISSUE TITLE
Sudden crash when modeling in FEBio Studio 2.1.1 (with FEBio 4.1)

### ISSUE THREAD

**Issue by antimonyz** [febiosoftware/FEBio#61] opened 2023-04-11 13:14 UTC
FEBio Studio 2.1.1 (with FEBio 4.1) suddenly crashed when I am trying to model multi-phasic contact, as guided by the FEBio Studio Webinar Biphasic Materials Part 2. The following steps are my operations:

Step 1: start a new multiphasic analysis model;
Step 2: create a slice at position (0,0,0) with parameters Radius=1.5, Height=1, Angle=180;
Step 3: in the mesh option, set the Mesh Parameters as Slices=16, Segments=8, Stacks=8, Z-bias=1, R-bias=1, then click "Apply";
Step 4: Click "Convert" and then change the mesh to "Editable mesh";
Step 5: Click "Boundary Layer" and set Bias=2, Segments=5, select the outer surface and click "Apply" - then the following dialog box appears and then FEBio Studio automatically closed.
![未命名1681218728](https://user-images.githubusercontent.com/59652808/231173384-7230f120-bc45-445c-b54a-3f458229c29b.png)

All the operations are the same as guided in Webinar, except I use the Multiphasic Analysis. The same operations in Biphasic Analysis are fine, but it failed in Multiphasic Analysis. 

Moreover, the same operations work well in FEBio Studio 1.9 (with FEBio 3.8).

Could you help to solve this issue?

**Comment by SteveMaas1978** [comment] 2023-10-02 15:21
I cannot reproduce this issue in FEBio Studio 2.3, so I assume this issue has been resolved. I'm closing the issue now, but let us know if you do continue to experience these problems.

**Closed as completed by SteveMaas1978** 2023-10-02 15:21 UTC
